#!/bin/sh

case "$1" in
    # delete files
    "C-d") xargs -I"{}" rm -- "{}";;
    "r")
        read FILE
        DIR=$(dirname "$FILE")
        echo | dmenu -p "Renaming $FILE to:" | xargs -I"{}" mv -- "$FILE" "$DIR/{}"
        ;;
    # copies absolute path to select file to clipboard
    "C-n")
        filenames=""
        while read filename; do
            filenames="\"$(readlink -e "$filename")\" $filenames"
        done
        echo -n "$filenames" | xclip -sel clip -i
        notify-send "Copied filenames to clipboard"
        ;;
    # copies image to clipboard
    "C-c")
        read FILE
        xclip -selection clipboard "$FILE" -t image/png
        notify-send "Copied image" "Copied '$FILE' to clipboard."
        ;;
esac
